version: "2"
services:
  app:
    container_name: "fusemachines-ai-training"
    build: .
    links:
      - db
    ports:
      - "5000:5000"
  db:
    image: mongo
    container_name: "mongodb"

    ports:
      - "27017:27017"